### PR TITLE
Release 0.5 with Python 2 support

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by SylvainCorlay** [comment]
@blink1073 you may need to add the msvc runtime as a runtime dependency.

**Comment by blink1073** [comment]
`winpty` already specifies it

**Comment by blink1073** [comment]
Couldn't hurt I suppose.

**Comment by SylvainCorlay** [comment]
Sorry I am using my phone and was only seeing a single commit....

**Comment by blink1073** [comment]
Updated both here and `winpty` to only use `vs2015_runtime` rather than the full `vc 14`

**Comment by blink1073** [comment]
Good to go!

**Pull request merged**
