### PR TITLE
Remove command to build all packages with VS 14

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@jjhelmus, we were using a command inside `bld.bat` to compile Pywinpty with VS 14 for all Python versions. After removing it, compilation in Python 2 fails.

Could you help us with this? Thanks!

**Comment by jjhelmus** [comment]
I didn't catch that line when I was building either, let me have a look.

**Comment by jjhelmus** [comment]
PR #11 uses the mingw-w64 toolchain to compile the extension for Python 2.7.  I think this is the best option short of adding VS 2008 support to winpty.

**Comment by ccordoba12** [comment]
Thanks @jjhelmus! Closing this one then.

**Pull request closed without merging**
