### PR TITLE
Update pywinpty build version to 0.2.1

### PR DESCRIPTION
**Pull request by andfoy**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Did you readd this feedstock through staged-recipes?

**Comment by andfoy** [comment]
@ccordoba12 No, I haven't readd it yet

**Comment by ccordoba12** [comment]
You need to, else you won't be able to do this update.

**Comment by andfoy** [comment]
See https://github.com/conda-forge/staged-recipes/pull/3758

**Comment by ccordoba12** [comment]
As with humanfriendly, you need to add the current recipe to staged-recipes. When you see a new, automatic Travis commit here, then you can merge this PR.

**Comment by ccordoba12** [comment]
The updated recipe won't be merged here, so you still need to merge this PR after the feedstock is updated.

**Pull request merged**
