### PR TITLE
Pin winpty to a working mingw build

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@jakirkham, @ocefpaf, how can we pin a package to a particular build number? We need `winpty 0.4.3 build 4`, but (for some reason) `conda build` is pulling  `winpty 0.4.3 build 2`.

**Comment by ocefpaf** [comment]
Looks like a typical bad solution from the coda solver :-/
I guess that `0.4.3 build 2` has less dependencies, has unpinned deps, or pinned to easy to solve deps... Anyway, since they are same version but you want a higher build number I guess that the best thing to do is to move the lower build number to the "broken" label.

**Comment by ccordoba12** [comment]
Thanks @ocefpaf, that's what we needed!

**Pull request merged**
